nrpetclinic/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'nrpetclinic.views.home', name='home'),
    # url(r'^nrpetclinic/', include('nrpetclinic.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    
    url(r'^petclinic/$', 'petclinic.views.index'),
    url(r'^petclinic/find_owners/$', 'petclinic.views.owners.find_owners'),
    url(r'^petclinic/owners/$', 'petclinic.views.all_owners'),
    url(r'^petclinic/owners/(?P<owner_id>\d+)$', 'petclinic.views.owners.owner'),
    
    url(r'petclinic/vets/$', 'petclinic.views.all_vets'),
    url(r'petclinic/weather/', 'petclinic.views.weather'),
    url(r'petclinic/rss_test/', 'petclinic.views.rss_test'),
    
    url(r'petclinic/error_page/', 'petclinic.views.exception_page'),
    url(r'petclinic/divide_by_zero/', 'petclinic.views.divide_by_zero'),
    
)

nrpetclinic/petclinic/models/owner.py
from django.db import models

class Owner(models.Model):
    first_name = models.CharField(max_length = 128)
    last_name = models.CharField(max_length = 128)
    address = models.CharField(max_length = 256)
    city = models.CharField(max_length = 128)
    telephone = models.CharField(max_length = 20)
    
    def __unicode__(self):
        return self.first_name + " " + self.last_name + "\n\t" + self.address + ", " + self.city
    
    class Meta:
        app_label = 'petclinic'

nrpetclinic/petclinic/models/pet.py
from django.db import models
from owner import Owner
from pet_type import PetType

class Pet(models.Model):
    name = models.CharField(max_length = 128)
    birth_date = models.DateTimeField("Date of Birth")
    owner = models.ForeignKey(Owner)
    pet_type = models.ForeignKey(PetType)
    
    def __unicode__(self):
        return self.name + "is a " + self.pet_type.name + " and belongs to " + self.owner.first_name + " " + self.owner.last_name
    
    class Meta:
        app_label = 'petclinic'

nrpetclinic/petclinic/models/pet_type.py
from django.db import models

class PetType(models.Model):
    name = models.CharField(max_length = 128)
    
    def __unicode__(self):
        return "Pet type: " + self.name
    
    class Meta:
        app_label = 'petclinic'

nrpetclinic/petclinic/models/specialty.py
from django.db import models

class Specialty(models.Model):
    name = models.CharField(max_length = 128)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        app_label = 'petclinic'

nrpetclinic/petclinic/models/vet.py
from django.db import models

from specialty import Specialty

class Vet(models.Model):
    first_name = models.CharField(max_length = 128)
    last_name = models.CharField(max_length = 128)
    specialties = models.ManyToManyField(Specialty)
    
    def __unicode__(self):
        return self.first_name + " " + self.last_name
    
    class Meta:
        app_label = 'petclinic'
        

nrpetclinic/petclinic/models/visit.py
from django.db import models

from pet import Pet

class Visit(models.Model):
    visit_date = models.DateTimeField()
    description = models.TextField()
    pet = models.ForeignKey(Pet)
    
    class Meta:
        app_label = 'petclinic'
        

nrpetclinic/petclinic/views/base.py
from django.template import Context, loader
from django.http import HttpResponse
from petclinic.models import *
from django.shortcuts import render_to_response

def index(request):
    return render_to_response('petclinic/home.html', {})

nrpetclinic/petclinic/views/error_pages.py
from petclinic.models import *
from django.shortcuts import render_to_response

def exception_page(request):
    raise NameError("This is a test error")
    return render_to_response("petclinic/error_pages/exception_page.html")

def divide_by_zero(request):
    ans = 1/0
    return render_to_response("petclinic/error_pages/divide_by_zero.html", {'ans' : ans})

nrpetclinic/petclinic/views/owners.py
from petclinic.models import *
from django.shortcuts import render_to_response

def all_owners(request):
    if 'last_name' in request.GET:
        all_owners = Owner.objects.filter(last_name__icontains=request.GET['last_name'])
    else:
        all_owners = Owner.objects.all()
    return render_to_response('petclinic/owners/all_owners.html', {'all_owners_list': all_owners})
    
def owner(request, owner_id):
    owner = Owner.objects.get(pk=owner_id)
    return render_to_response('petclinic/owners/owner.html', {'owner': owner})

def find_owners(request):
    return render_to_response("petclinic/owners/find_owners.html", {})
    

nrpetclinic/petclinic/views/vets.py
from django.template import Context, loader
from django.http import HttpResponse
from petclinic.models import *
from django.shortcuts import render_to_response

def all_vets(request):
    all_vets = Vet.objects.all()
    return render_to_response('petclinic/vets/all_vets.html', { 'all_vets_list': all_vets })
    
def vet(request, vet_id):
    vet = Vet.objects.get(pk=vet_id)
    return render_to_response('petclinic/vets/vet.html', {'vet': vet})

nrpetclinic/petclinic/views/weather.py
from petclinic.models import *
from django.shortcuts import render_to_response

import pywapi
import random
import feedparser

def weather(request):
    locations = ["94041", "90008", "97202", "94110", "10024", 
                 "02111", "60605", "23454", "32804", "75204", 
                 "98112", ]
    forecasts = []
    for location in random.sample(locations, 4):
        forecasts.append(pywapi.get_weather_from_yahoo(location))
    return render_to_response("petclinic/weather/weather_basic.html", { 'forecasts': forecasts })


def rss_test(request):
    url = "http://rss.cnn.com/rss/cnn_topstories.rss"
    accessed = []
    feed = feedparser.parse(url.encode('utf-8'), modified = accessed, etag = 100)
    feed_entries = []
    for entry in feed['entries']:
        feed_entries.append(entry)
    
    return render_to_response("petclinic/weather/rss_test.html", { 'feed': feed_entries })

nrpetclinic/petclinic/templates/petclinic/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
    <head>
        <title>Django Petclinic | {% block title%}{% endblock %}</title>
        <link href="{{ STATIC_ROOT }}/static/petclinic.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        {% include 'petclinic/header.html' %}
        <div id="main">
        {% block content %}{% endblock %}
        </div>
        {% include 'petclinic/footer.html' %}
    </body>
</html>

nrpetclinic/petclinic/templates/petclinic/error_pages/divide_by_zero.html
{% extends 'petclinic/base.html' %}

{% block title%}Home{% endblock %}

{% block content %}
<h1>This is just a placeholder page.</h1>
{% endblock %}

nrpetclinic/petclinic/templates/petclinic/error_pages/exception_page.html
{% extends 'petclinic/base.html' %}

{% block title%}Home{% endblock %}

{% block content %}
<h1>This is just a placeholder page.</h1>
{% endblock %}

nrpetclinic/petclinic/templates/petclinic/footer.html
<footer>
    <table class="footer">
        <tr>
            <td><a href="/petclinic/">Home</a></td>
        </tr>
    </table>
</footer>

nrpetclinic/petclinic/templates/petclinic/header.html
<img src="/static/pets.png" style="position: relative; right: 30px" align="right" />

nrpetclinic/petclinic/templates/petclinic/home.html
{% extends 'petclinic/base.html' %}

{% block title%}Home{% endblock %}

{% block content %}
<h1>Django PetClinic</h1>
<ul>
    <li><a href="/petclinic/find_owners/">Find Owners</a></li>
    <li><a href="/petclinic/vets/">Vets</a></li>
    <li><a href="/petclinic/weather/">Weather page</a></li>
    <li><a href="/petclinic/rss_test/">RSS Feed Test Page</a></li>
</ul>
{% endblock %}

nrpetclinic/petclinic/templates/petclinic/owners/all_owners.html
{% extends 'petclinic/base.html' %}

{% block title %}All Owners{% endblock %}

{% block content %}
<h1>Listing Owners</h1>
{% if all_owners_list %}
    <table>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>City</th>
            <th>Telephone</th>
            <th>Pets</th>
        </tr>
    {% for owner in all_owners_list %}
    <tr>
        <td><a href="/petclinic/owners/{{ owner.id }}">{{ owner.first_name }} {{ owner.last_name }}</a></td>
        <td>{{ owner.address }}</td>
        <td>{{ owner.city }}</td>
        <td>{{ owner.telephone }}</td>
        <td>
            {% for pet in owner.pet_set.all %}
            {{ pet.name }}
            {% endfor %}
        </td>
    </tr>
    
    {% endfor %}
    
    </table>
{% else %}
    <p>There are currently no owners to display</p>
{% endif %}
{% endblock %}

nrpetclinic/petclinic/templates/petclinic/owners/find_owners.html
{% extends 'petclinic/base.html' %}

{% block title%}Home{% endblock %}

{% block content %}
<form action="/petclinic/owners/" method="get">
    <table>
        <tr>
            <th>
                <label for="last_name">Last name:</label><br />
                <input type="text" name="last_name" id="last_name"/>
            </th>
        </tr>
        <tr>
            <td><p class="submit"><input type="submit" value="Find Owners" name=""></p></td>
        </tr>
    </table>
</form>
{% endblock %}

nrpetclinic/petclinic/templates/petclinic/owners/owner.html
{% extends 'petclinic/base.html' %}

{% block title %}{{ owner.first_name }}{{ owner.last_name }}{% endblock %}

{% block content %}
<h2>Owner Information</h2>

<table>
    <tr>
        <td>Name</td>
        <td>{{ owner.first_name }}&nbsp;{{ owner.last_name }}</td>
    </tr>
    <tr>
        <td>Address</td>
        <td>{{ owner.address }}</td>
    </tr>
    <tr>
        <td>City</td>
        <td>{{ owner.city }}</td>
    </tr>
    <tr>
        <td>Telephone</td>
        <td>{{ owner.telephone }}</td>
    </tr>
</table>

<h2>Pets and Visits</h2>
{% for pet in owner.pet_set.all %}
    <table>
        <tr valign="top">
            <td>
                <table>
                    <tr>
                        <th>Name</th>
                        <td>{{ pet.name }}</td>
                    </tr>
                    <tr>
                        <th>Birthdate</th>
                        <td>{{ pet.birth_date }}</td>
                    </tr>
                    <tr>
                        <th>Type</th>
                        <td>{{ pet.pet_type.name }}</td>
                    </tr>
                </table>
            </td>
            <td valign="top">
                <table>
                    <tr>
                        <thead>
                            <th>Visit Date</th>
                            <th>Description</th>
                        </thead>
                        {% for visit in pet.visit_set.all %}
                        <tr>
                            <td>{{ visit.visit_date }}</td>
                            <td>{{ visit.description }}</td>
                        </tr>
                        {% endfor %}
                    </tr>
                </table>
            </td>
        </tr>
    </table>
{% empty %}
    <p>There are no pets for this owner.</p>
{% endfor %}
{% endblock %}

nrpetclinic/petclinic/templates/petclinic/vets/all_vets.html
{% extends 'petclinic/base.html' %}

{% block title %}All Vets{% endblock %}

{% block content %}
<h1>Listing Vets</h1>

<table>
    <tr>
        <th>Name</th>
        <th>Specialties</th>
    </tr>
    {% for vet in all_vets_list %}
        <tr>
            <td>{{ vet.first_name }}&nbsp;{{ vet.last_name }}</td>
            <td>
                {{ vet.specialties.all|join:", " }}
            </td>
        </tr>
    {% empty %}
        <p>There are no vets to display</p>
    {% endfor %}
</table>

{% endblock %}

nrpetclinic/petclinic/templates/petclinic/weather/rss_test.html
{% extends 'petclinic/base.html' %}

{% block title %}RSS feed Test Page{% endblock %}

{% block content %}
<table>
	<tr>
		<th>Title</th>
		<th>Link</th>
		<th>Summary</th>
	</tr>
	{% for entry in feed %}
	<tr>
		<td>{{ entry.title }} </td>
		<td><a href="{{ entry.link }}" >Full entry</a></td>
		<td>{{ entry.summary|safe }}</td>
	</tr>
	{% endfor %}
</table>

{% endblock %}

nrpetclinic/petclinic/templates/petclinic/weather/weather_basic.html
{% extends 'petclinic/base.html' %}

{% block title %}Weather Test Page{% endblock %}

{% block content %}

<table>
    <tr>
        <th>City</th>
		<th></th>
        <th>link</th>
    </tr>
	{% for f in forecasts %}
	<tr>
	    <td valign="top">{{ f.location.city }}</td>
	    <td>
	    	<table>
	    		<tr>
	    			<td valign="top">Conditions</td>
	    			<td colspan="2">
	    				{{ f.condition.text }}<br/>
	    				Temp: {{ f.condition.temp }} {{ f.units.temperature }}<br/>
	    				Wind: {{ f.wind.speed }} {{ f.units.speed }}
	    			</td>
	    		</tr>
	    		<tr>
	    			<td>Sunrise/Sunset</td>
	    			<td>{{ f.astronomy.sunrise }}</td>
	    			<td>{{ f.astronomy.sunset }}</td>
	    		</tr>
	    	</table>
	    </td>
	    <td valign="top"><a href="{{ f.link }}">Full Weather</a></td>
	</tr>
	{% endfor %}
</table>

{% endblock %}